# Generated by Django 3.0.1 on 2020-01-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal',
        ),
    ]
