# Generated by Django 3.0.1 on 2020-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_meal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('type', 'day'), name='unique_meal'),
        ),
    ]
