# Generated by Django 3.0.1 on 2020-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200130_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('meal', models.CharField(choices=[('V', 'Veg'), ('NV', 'Non-Veg')], default='V', max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
