# Generated by Django 3.0.1 on 2020-01-31 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0005_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extras',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExtrasOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Extras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
