# Generated by Django 3.0.1 on 2020-01-31 09:20

from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[registration.validators.validate_phone]),
        ),
    ]
